KJeff01/camBalance

script/campaign/transitionTech.js
stats/research.json

I tried to move the second Cannon damage upgrade to Alpha 06 and the Medium Cannon as a prerequisite of it, but it doesn't work. What am I doing wrong?

Cannon research change

---

script/campaign/cam1-3.js
script/campaign/cam1-4a.js
script/campaign/cam1-5.js
script/campaign/cam1-7.js
script/campaign/cam1c.js
script/campaign/cam1ca.js
stats/research.json

With the changes for the MRA, the MRA used by the NP became too strong according to Discord member Dziq. I moved the rocket damage upgrade 2 to Alpha 08 and upgrade 3 to Alpha 11. Therefore the values for the upgrades also changed and some damage upgrades get stripped from the Scavs and the NP.

Rocket changes

---

script/campaign/cam3-2.js

I made some tests and even with Insane difficulty the player has too much time for preparation. Cutting the reinforcement time for the NE group to 3 minutes gives him not enough time, therefore I set it to 3.5 minutes. I also set the reinforcement time for the SW group 30 seconds shorter due to the same reasons. This also avoids that both groups are coming together and causing insolvable problems. Bringing back phantomFactoryNE() is also too tough.

Updating Gamma 04

---

stats/weaponmodifier.json

Even that most players will never see the modifiers, from a logical point it makes no sense that Hover tanks are having a lower modifier than tracked tanks. Therefore I switched these modifiers in ALL ROUNDER and ANTI TANK. Also the modifiers in ARTILLERY ROUND against Hover and wheeled tanks are too high in my eyes, so they get decreased. Even though the modifier against legged units in ARTILLERY ROUND is higher than the modifier in ANTI PERSONNEL I didn't change it because it would become too difficult to destroy Nexus Cyborgs with artillery. Especially in Gamma 04.

weaponmodifier adjustment

---

stats/weapons.json

There were some complaints about the strength of the Scav flamer. Therefore, after some tests, I decreased the ROF to 20 from 30.

Scav Flamer ROF change

---

script/campaign/cam1-4a.js
stats/weapons.json

Feedback from Discord member Dziq and own tests showed that the unit production of the NP is too fast and the MRP too powerful. Therefore the throttles for both factories are increased and the MRP a bit nerfed.

Alpha 08 tweaks

---

script/campaign/cam1-5.js
stats/research.json

Discord member Dziq mentioned that from a logical point it makes more sense to research the Scorpion body earlier than the Python body. Therefore the Scorpion body is moved from Alpha 09 to Alpha 08 with Composite Alloys Mk1 as the prerequisite.

Scorpion move

---

script/campaign/cam3-1.js
script/campaign/cam3-2.js
script/campaign/cam3-a.js
stats/research.json

Changed the values for Nexus wall/structure defense upgrades.
Gives now one upgrade for Gamma 1 and 2, two for Gamma 3 and 4, and three for Gamma 6.
Changed the values for Nexus only upgrades 10 and 11. The change for upgrade 11 seems very high but if my calculations are right it's necessary to keep Nexus' walls/structures strong enough against the Rail Gun in Gamma 9.

Nexus wall/structure armor changes

---

wrf/cam3/cam3-4/labels.json

Tests showed that produced Cyborgs are blocked in their way to attack the player with the result that too many units arrive at the front at once. Therefore the rally points are moved to avoid any blocking.

Move rally points in Gamma 9

---

stats/research.json

The Pepperpot obsoletes the Bombard and because the Bombard is stronger than the MRA it should also obsolete the MRA.

Adding the MRA to the red components of the Pepperpot

---

stats/research.json

Because the MRA became too powerful, the Rocket damage upgrade 4 is decreased after one Beta 1 run with the MRP and additional weapon tests

Decreasing Rocket damage upgrade 4

---

stats/research.json

Weapon tests showed that the MRA and the MRP are too powerful after Beta 3. Therefore the damage upgrade 5 is decreased.

Decrease Rocket damage upgrade 5

---

script/campaign/cam2-2.js

The queue for vtolAttack is added to the time in the vtolAttack function. With the result, that it last too long until the first VTOL attack takes place. Therefore the queue is decreased to one second.

Changing queue of Vtol attacks in Gamma 04

---

stats/weapons.json

Tests showed that the Commander is still working with the damage zero. Now he only marks the targets and deals no longer damage. As it should be in my eyes.

Giving the Commander the damage zero

---

stats/weapons.json

Because the Ground Shaker is the "Heavy Howitzer" it should have the highest base damage. Therefore the base damage is slightly increased.

Increasing the Ground Shaker base damage a bit

---

stats/weapons.json

numRounds is superfluous for the Needle Gun. Somehow I missed that all the time.

Removing numRounds for the Needle Gun

---

script/campaign/cam2-5.js

Especially with Insane difficulty, it's way too difficult to make any progress with the current unit production. Therefore the factory throttles are increased to values comparable with the later levels.

Increasing factory throttles in Beta 06

---

stats/research.json

Tests showed that it's necessary to increase the damage upgrade 6 to keep the MRP and the MRA viable choices.

Increase Rocket damage upgrade 6

---

stats/research.json

In my calculations, the goal was that cannons are dealing between 2/3 and 3/4 of the damage an anti-tank weapon deals to a tank. This goal was missed due to the wrong accuracy values I set in my spreadsheet. Here are the tested changes (up to Beta 09) to the cannon damage upgrades that reach this goal again.

Cannon rebalance

---

stats/research.json
stats/weaponmodifier.json

Discord member VanitysFiend mentioned that the LC in Alpha 05 and Alpha 06 is weaker than the HMG and my calculations showed that he's right. Therefore the weaponmodifier for anti-personnel weapons is changed and the second cannon damage upgrade moved back to Alpha 04 from Alpha 06.

Light Cannon balance changes

---

script/campaign/cam2-5.js

Reverts the previous timer change for the dam hovers because I missed that the timer was in Seconds and not in Minutes.

Beta 6 Hover activation timer change

---

stats/weapons.json

Tests in Gamma 04 showed that the HVC is too weak against cyborgs in comparison with the AC to be a viable option. Therefore the HVC gets a damage and hitpoints buff.

HVC damage and hitpoints buff

---

stats/research.json
stats/weapons.json

Decreasing the base Damage of the AC to 52 because of being to strong with 53. According to a feedback from Discord member Brutaz the MRP is too powerful in Alpha 06. Therefore the first damage upgrade is decreased to 30 and the second increased to 20.

Weapon adjustments

---

stats/body.json

Due to complains that Nexus cyborgs are to strong the armour got decreased.

Gamma cyborg armour decrease

---

stats/weapons.json

These weapons were doing the same damage as tank variants since the previous few VTOL weapon tweaks. These are my temporary solutions until someone else wants to do more refined calculations.
1. flashlight
2. pulse laser
3. needle
4. rail gun
5. scourge missile
6. bunker buster

Buff VTOL weapons that did the same damage as a tank version

---

script/campaign/cam3-4.js
wrf/cam3/cam3-4/labels.json

Remove destruction of VTOLs at start of SW base being sited, instead, just protect the HQ with a force-field wave against them.
Take over chance attack happens on all difficulties with varied chances now. Commanders ignored for initial hit.
Finally, some added checks to see if the HQ was destroyed before base detection to prevent warnings.

Change Nexus hacking Gamma 9

---

script/campaign/cam2-6.js
script/campaign/cam2-d.js
script/campaign/transitionTech.js
stats/research.json
stats/structuremodifier.json

- Moves Turbo-Charged Engine Mk2 into Beta 7 after the first research module upgrade.
- Makes Bunker Buster 1 shot all bunker busters (at least as far as you have to go up against, last Plasteel upgrades keep them alive).
- Bump Depleted Uranium MG Bullets upgrade so AC doesn't outpace AG during the brief window Gamma 1 starts you with the Mk2 upgrade. AC wins in this window currently due to baseline damage being buffed to 52 and the Nexus cyborg nerf.

Tweaks before 4.5.0

---

script/campaign/cam1-7.js
script/campaign/cam1-d.js
script/campaign/libcampaign_includes/artifact.js
script/campaign/libcampaign_includes/events.js

This allows the campaign library to notice and use pre-placed artifacts instead of relying on them appearing only by position if you wanted one to appear out in the open.
The means to add and remove artifacts individually is also supported (and used in Alpha 11 for example purposes).
Also noticed that eventDestroyed() runs after eventPickup, so we don't want to run code in that event if the destroyed object is an artifact. Not sure if this is new master behavior or not.

Allow using map-placed artifacts

---

script/campaign/transitionTech.js
stats/research.json
stats/weapons.json

- Adds 1 point of base damage to HMG and AG to help the distance between them and a flamer's periodical damage. Flashlight should still be stronger most of the time than AG, assuming it doesn't miss too much.
- Adds a ROF upgrade for Ripple Rockets after Hellstorm, mostly cause GS and HS have huge splash damage and RR can only hit a single target.
[camBalance.zip](https://github.com/user-attachments/files/16034516/camBalance.zip)

Buff MG damage and add new RR ROF upgrade

---

stats/research.json

Mostly cuts all defense/wall price and research time in half.
Non-artillery emplacements, and  base building material upgrades were reduced to 25%.
---
This will massively help reduce how boring it is to watch research tick down on missions like Alpha 5, Beta 5, and Gamma 3/6/7, and any others with large amounts of defense related research topics. It also fixes absurd costs on Gamma tier defenses which don't need to cost 450(!) power. And, it helps conserve power for Insane runs on missions like Beta 1 and Gamma 3 where power is very important.

Reduce price/time of defense related research
