KJeff01/camBalance

script/campaign/cam2-1x.js

Send the east Cyborg group to attack instead to patrol.

Beta 02 changes

---

stats/weapons.json

Increased ROF for Inferno Flamer to match the regular Flamer

Inferno adjustment

---

script/campaign/cam1-2.js
script/campaign/cam1-3.js
script/campaign/cam1-4a.js
script/campaign/cam1-5.js
script/campaign/cam1-7.js
script/campaign/cam1a-c.js
script/campaign/cam1c.js
script/campaign/cam1ca.js

Adding some missed researches for the NP and the Scavs

Alpha Research Tweaks

---

messages/resmessages23.json
script/campaign/transitionTech.js
stats/research.json

During the Gamma campaign, Cannons are getting 3 more damage and 3 more ROF upgrades. Due to the higher armour of the Nexus tanks, the advantage of the Tank Killer against vehicles remains big enough. The three ROF upgrades are making the advantage too small. Therefore I added three new Slow Rocket ROF upgrades.

Gamma research addition

---

script/campaign/cam1-3.js
script/campaign/cam1-4a.js
script/campaign/cam1-5.js
script/campaign/cam1-7.js
script/campaign/cam1c.js
script/campaign/templates.js
stats/weapons.json

Took me some time but I fixed the error messages. Hooray

Templates fix

---

script/campaign/cam2-7.js
stats/research.json
wrf/cam2/sub2-7/labels.json

Brings the Improved Bomb Warhead back to Beta 09 as in version 4.0.0 beta 1

Bomb upgrade transfer

---

stats/research.json

@highlander1599 Maybe fixes #28.

Missile research tweaks.

---

stats/research.json

After starting camBalance with 4.0.0 beta2 I found these two research errors in the log file

Research errors fix

---

script/campaign/cam1-4a.js
wrf/cam1/sub1-4/labels.json

Fixes #52 without moving the MRP tower.

More Alpha 08 tweaks

---

script/campaign/cam1-4a.js

According to feedback from Discord some changes to make Alpha 08 doable with higher difficulties.

Alpha 08 tweaks

---

script/campaign/cam3-4.js
script/campaign/cam3-a.js
script/campaign/cam3-ad1.js

Some tweaks for the Gamma campaign. With these changes, we are ready for the final tests. I will start a new campaign with insane difficulty after you merged this PR. The balance for the MRP is still not really finished and it's unclear if the MRA should shoot salvos again or not. Everything else is fine for normal difficulty.

Gamma tweaks

---

stats/research.json

Some weapon tests showed that the MRP became too good in comparison with the Lancer. Therefore it gets a bit nerfed.

Some MRP adjustments

---

messages/resmessages1.json
messages/resmessages12.json
messages/resmessages2.json
messages/resmessages23.json
messages/resmessages3.json
messages/resmessagesall.json

With new and changed modifiers some research messages were no longer correct

Research messages update

---

stats/research.json
stats/weapons.json

The last MRP PR underestimated the influence on the MRA and made it too weak. Therefore the damage values of the MRA and the MRP have changed and the damage research upgrade values adjusted. Alpha campaign is tested, Beta campaign not yet.

Rocket update

---

stats/weapons.json

Now that version 4.1 is on the way we should make the RR the Anti Tank artillery and keep the Howitzers the Anti Cyborg artillery.

Making the RR an "Anti Tank artillery"

---

script/campaign/cam2-2.js
script/campaign/cam2-8.js
script/campaign/cam2-a.js
script/campaign/cam2-b.js
script/campaign/cam2-c.js

Replacing obsolete build order templates

Collective truck defense

---

script/campaign/cam2-6.js

Sends the southeastern cyborgs always to the player LZ and reduces the queue of the time based factories to 5 minutes

Beta 08 tweaks

---

script/campaign/cam2-7.js
wrf/cam2/sub2-7/labels.json

My tests showed that Beta 09 is still doable with truckDefense and Insane difficulty. Still waiting for feedback on Discord.

Implement truckDefense into Beta 09

---

stats/weapons.json

After some feedback from Discord members Rafs and Steelpoint the Laser weapons get buffed.

Laser buff

---

script/campaign/cam2-2.js
script/campaign/cam2-5.js
script/campaign/cam2-6.js
script/campaign/cam2-7.js
script/campaign/cam2-a.js
script/campaign/cam2-b.js
script/campaign/cam2-c.js
script/campaign/cam2-d.js

Make some queues and timers depending on the difficulty

Beta timer changes

---

script/campaign/cam3-2.js

Make the patrol groups queue depending on the difficulty

Gamma 4 queue change

---

script/campaign/cam2-8.js

Making the Vtol attack depending on the difficulty

Beta 10 Vtol attack timer change

---

script/campaign/cam1-1.js

Bringing back the HMG templates for Hard and Insane difficulty

Alpha 03 tweaks

---

stats/research.json
stats/weapons.json

Due to complains that Flashlight is too weak in comparison with the AG the base damages of the Lasers got increased and the damage upgrade values adjusted.

Laser changes

---

script/campaign/cam2-7.js
script/campaign/cam2-8.js
script/campaign/cam2-end.js
script/campaign/cam3-1.js
script/campaign/cam3-a.js
script/campaign/transitionTech.js
stats/research.json

Moves Depleted Uranium bullets into Beta 9.
Moves Depleted Uranium bullets Mk2 at the start of Gamma 1.
Added a new Flamer Fast Loader Upgrade at the start of Gamma 1.

Move around some MG upgrades; New Flamer ROF upgrade

---

script/campaign/cam1-7.js
script/campaign/cam1a.js
script/campaign/cam2-6.js
script/campaign/cam2-7.js
script/campaign/cam2-8.js
script/campaign/cam2-b.js
script/campaign/cam2-c.js
script/campaign/cam3-a.js
script/campaign/cam3-ab.js
script/campaign/cam3-ad1.js
script/campaign/cam3-ad2.js
script/campaign/cam3-b.js
script/campaign/cam3-c.js
script/campaign/libcampaign.js
script/campaign/libcampaign_includes/artifact.js
script/campaign/libcampaign_includes/misc.js
script/campaign/libcampaign_includes/nexus.js
script/campaign/libcampaign_includes/production.js
script/campaign/libcampaign_includes/research.js
script/campaign/libcampaign_includes/transport.js
script/campaign/libcampaign_includes/truck.js
script/campaign/libcampaign_includes/victory.js

Remove some hardcoded strings. Still, people that change everything will make life 10 times harder on themselves.

hardcode removal
